/* eigen_topology_tracker.h
 *
 * This file contains the topology tracking engine. It processes any updates
 * that are generated by the backend and turns it into a graph.
 *
 * Information can be accessed in two ways:
 *      1. Distance from the root node (depth)
 *      2. Node connections (topology)
 *
 * Depth information is useful for determining which module is where in a parallel
 * robot such as a hexapod. The root node (or hub) is at depth 0, while the next level
 * down would be the first joint of each leg.
 *
 * Depth information can be inferred from topology information, but it is not
 * necessarily efficient or straightforward to calculate. Depth information is
 * precalculated by this class to make GUI implementations easier.
 *
 * Topology information is useful for determining what modules comprise a serial unit
 * such as a leg.
 *
 * Created 2021 by Nick Paiva
 */

#ifndef EIGEN_TOPOLOGY_TRACKER_H
#define EIGEN_TOPOLOGY_TRACKER_H

#include "eigen_utils.h"
#include "eigen_responses/eigen_response.h"
#include "eigen_commands/eigen_command.h"
#include "eigen_update.h"
#include <vector>
#include <deque>
#include <map>

class EigenTopologyTracker{
public:
    EigenTopologyTracker();
    ~EigenTopologyTracker();

    //Update processing interface
    void add_update(EigenUpdate *update);
    void add_update(std::vector<EigenUpdate *>);
    void process_updates();

    //Depth of the deepest node
    eigen_addr_t max_depth() const;

    /* Node class, used to create a graph */
    class Node{
    public:
        Node(eigen_addr_t address, EigenTopologyTracker *tracker);
        Node(eigen_addr_t address, EigenTopologyTracker *tracker, Node *parent);
        ~Node();

        /* Getters */
        eigen_addr_t address() const; //What is the address of the module represented by this node
        eigen_addr_t port_id() const; //What port of this module's parent is this node connected to
        std::string port_name() const; //Name of the port this module is connected to
        std::string text() const; //String representation of this module
        const Node *parent() const; //Get the parent of this node
        int childNumber() const; //Get this node's index in its parent's child map
        Node *parent(); //Parent of this node, but not const
        const std::map<eigen_addr_t, Node *> children() const; //What are the children of this node
        const Node *child(eigen_addr_t index) const; //Get the nth child of this node

        /* Setters */
        void update_depth(Node *caller = nullptr);
        void set_parent(Node *parent);
        void set_port(eigen_addr_t id, std::string name);
        void add_child(Node *child);
        void remove_child(Node *child);
        void remove_child(eigen_addr_t child_addr);
        bool has_child(eigen_addr_t child) const;
        bool is_root() const;
        eigen_addr_t depth() const;

    private:
        mutable std::recursive_mutex mutex_;        //Mutex for thread safety
        eigen_addr_t addr_;                         //Address of module this represents
        std::map<eigen_addr_t, Node *> children_;   //Children of this node
        Node *parent_;                              //Parent of this node
        eigen_addr_t port_id_;                      //ID of the port this node is connected to
        std::string port_name_;                     //Name of the port this node is connected to
        eigen_addr_t depth_;                        //Depth in the tree
        EigenTopologyTracker *tracker_;             //Reference to owner
    };

    //Topology information functions
    const Node *get_node(eigen_addr_t address) const;
    const Node *root_node() const;
    const std::vector<Node *> get_depth_list(eigen_addr_t depth) const;

private:
    mutable std::recursive_mutex mutex_;                            //Mutex for thread safety

    Node *add_node(eigen_addr_t address, Node *parent = nullptr); //Helper to add a new node
    void remove_node(eigen_addr_t address); //Helper to remove a node by address key
    void remove_depth(Node *node, eigen_addr_t depth); //Helper to remove a node from the depth list
    void add_depth(Node *node, eigen_addr_t depth); //Helper to add a node to the depth list

    std::deque<EigenUpdate *> updates_; //Update queue
    Node *root_node_; //Root node of graph
    std::map<eigen_addr_t, Node *> node_map_; //Map of addresses to nodes
    std::vector<std::vector<Node *>> depth_list_; //List of nodes organized by depth
};

#endif
